### ISSUE TITLE
WoW crashes with UnitXP_SP3.dll

### ISSUE THREAD

**Issue by Ge3e** [allfoxwy/UnitXP_SP3#1]
Hello,  thanks for the great mod. WoW crashes with UnitXP_SP3.dll enabled when I jump on the boat between Auberdine and Darnassus (Rut'theran Village) in the Veiled Sea. If I disable the UnitXP_SP3.dll it doesn't happen. 

Question: Do I have to use the sideload-DLL.dll as well? I launch the game with VanillaFixes and only enable the UnitXP_SP3.dll in the dll.txt file. Is this correct? I get the same crashing with both ways set.

Thank you.

**Comment by allfoxwy** [comment]
Greetings.

sideload-DLL.dll is the included loader program. You could delete it and use VanillaFixes loader if you would like to.

Both sideload-DLL.dll and VanillaFixes loader read `dlls.txt` in the same way.

About the game crash, could you post a image of error message? In fact I got 2 crashes either, and yes on boat. But mine was from booty bay and theramore.

I would see what I can do.

**Comment by allfoxwy** [comment]
Should be fixed by 2a9c576ef168d8a73df4c44bcb795f410015fffd

Thank you for report it in. I did have suspect but not sure until I see you are experiencing it either.

If you find edge case that crash the same way (in theory, there are edge cases), please take a screenshot and feel free to reopen this issue.

**Comment by Ge3e** [comment]
Thanks for looking in to this and thanks for the mod. I'll report back.

**Comment by Ge3e** [comment]
I can confirm that, it is now working 100% now on the boats. Thank you.
